### ISSUE TITLE
where to go next after 0: setup? no link provided.

### ISSUE THREAD

**Issue by ratio91** [KILTprotocol/kilt-workshop-101#15]
please provide a link, so workshop participants can navigate the course easier. thank you!

**Comment by wischli** [comment]
Hi ratio91. You should easily be able to navigate through the tutorial by either

(1) Going to the next page at the bottom of each page (see right corner)

<img width="926" alt="Screenshot 2020-10-13 at 11 57 09" src="https://user-images.githubusercontent.com/26296386/95846169-67327380-0d4b-11eb-9eed-b94394fb0883.png">

(2) Or going from top to bottom in the nav menu

<img width="265" alt="Screenshot 2020-10-13 at 11 58 37" src="https://user-images.githubusercontent.com/26296386/95846196-70234500-0d4b-11eb-8be2-9e73796ae687.png">

**Comment by ratio91** [comment]
ah, the readme was missleading - I thought this is just a github repo.
using the hosted website this obviously works.

suggestion: instead of displaying the setup.md on github, please display a genereal readme containing a short statement that this is a github page and not a repo to clone ;-) thanks.

**Comment by wischli** [comment]
> suggestion: instead of displaying the setup.md on github, please display a genereal readme containing a short statement that this is a github page and not a repo to clone ;-) thanks.

I definitely agree. Thanks for the suggestion!

**Comment by wischli** [comment]
Fixed in db169326f811ca6946db415d73438f37f4da5a6f
